# -*- coding: utf-8 -*-
"""DimReduc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M157j5xKyHJSA9vvjs8YSEiR2DEhtadJ
"""

#DIMENSIONALITY REDUCTION; CONTROL: [PCA 100> UMPA 35], 100nn, 0.1md
from umap import UMAP
from sklearn.decomposition import PCA
import numpy as np
import cuml
from cuml import UMAP
import cupy as cp
import json
import gc

from google.colab import drive
drive.mount('/content/drive')

all_embeddings = np.load('/content/drive/MyDrive/all_embeddings_clean.npy')  # shape: (n_posts, dim)
all_embeddings = all_embeddings.astype(np.float32, copy=False)

#SAMPLING OPTION

with open('/content/drive/MyDrive/all_ids_clean.json') as f:
    all_ids = json.load(f)
N = len(all_ids)
#sample_size = int(N // 15)
sample_size = 7000000

np.random.seed(42)  # For reproducibility
sample_indices = np.random.choice(N, size=sample_size, replace=False)

sample_embeddings = all_embeddings[sample_indices]
post_ids        = [all_ids[i] for i in sample_indices]

with open('/content/drive/MyDrive/all_ids_clean.json') as f:
    all_ids = json.load(f)
#load sampled ids
with open('/content/drive/MyDrive/sample_ids_50D_100PCA_7M.json') as f:
    sampled_ids = json.load(f)

#convert to set for lookup
sampled_id_set = set(sampled_ids)

#Find unsampled indices

unsampled_indices = [i for i, id in enumerate(all_ids) if id not in sampled_id_set]
unsampled_indices = np.array(unsampled_indices)

#Turn to numpy array
unsampled_indices = np.array(unsampled_indices)
sample_embeddings = all_embeddings[unsampled_indices]
post_ids        = [all_ids[i] for i in unsampled_indices]

#BEST RESULTS
pca = PCA(n_components=150, random_state=42)
emb_pca = pca.fit_transform(sample_embeddings)
#del sample_indices; gc.collect()
del all_embeddings; gc.collect()
#del sample_embeddings; gc.collect()

emb_pca = emb_pca.astype(np.float32, copy=False)

X_gpu = cp.asarray(emb_pca)

del emb_pca

# Initialize cuML UMAP
umap_gpu = UMAP(n_components=50, n_neighbors=50, random_state=42, output_type='numpy', min_dist = 0.01)

# Fit and transform ON THE GPU (2 hours about for 16MIL posts, comp = 50, n_neigh = 15, GPU RAM at ___
# 50 min for 7M, nn 50, comp 50, md 0.01, GPU at 12.1GB)
emb_umap = umap_gpu.fit_transform(X_gpu)

# emb_umap is a NumPy array (back on CPU), shape: (n_posts, dimensions)
print(emb_umap.shape)

# Save as .npy
np.save('/content/drive/MyDrive/umap_embeddings_50D_150PCA_7M.npy', emb_umap)
with open('/content/drive/MyDrive/sample_ids_50D_150PCA_7M.json', 'w') as f:
    json.dump(post_ids, f)

#PCA CONTROL
pca = PCA(n_components=100, random_state=42)
emb_pca = pca.fit_transform(sample_embeddings)
del all_embeddings; gc.collect()

#DIMENSIONALITY REDUCTION CONTROL
# Assume sample_embeddings is a NumPy array (float32)
# Convert to cupy (GPU array)

X_gpu = cp.asarray(sample_embeddings)

# Initialize cuML UMAP
umap_gpu = UMAP(n_components=35, n_neighbors=100, random_state=42, output_type='numpy', min_dist = 0.1)

# Fit and transform ON THE GPU (2 hours about for 16MIL posts, comp = 50, n_neigh = 15, GPU RAM at ___)
emb_umap = umap_gpu.fit_transform(X_gpu)

# emb_umap is a NumPy array (back on CPU), shape: (n_posts, dimensions)
print(emb_umap.shape)

# Save as .npy
np.save('/content/drive/MyDrive/umap_embeddings_CONTROL.npy', emb_umap)
with open('/content/drive/MyDrive/sample_ids_CONTROL.json', 'w') as f:
    json.dump(post_ids, f)

#DIMENSIONALITY REDUCTION 0.25md

# Assume sample_embeddings is a NumPy array (float32)
# Convert to cupy (GPU array)

X_gpu = cp.asarray(emb_pca)

# Initialize cuML UMAP
umap_gpu = UMAP(n_components=35, n_neighbors=100, random_state=42, output_type='numpy', min_dist=0.25)

# Fit and transform ON THE GPU (2 hours about for 16MIL posts, comp = 50, n_neigh = 15, GPU RAM at ___)
emb_umap = umap_gpu.fit_transform(X_gpu)

# emb_umap is a NumPy array (back on CPU), shape: (n_posts, dimensions)
print(emb_umap.shape)

# Save as .npy
np.save('/content/drive/MyDrive/umap_embeddings_100_35D_100nn_0.25md.npy', emb_umap)
with open('/content/drive/MyDrive/sample_ids_100_35D_100nn_0.25md.json', 'w') as f:
    json.dump(post_ids, f)

#DIMENSIONALITY REDUCTION 0.01md

# Assume sample_embeddings is a NumPy array (float32)
# Convert to cupy (GPU array)

X_gpu = cp.asarray(emb_pca)

# Initialize cuML UMAP
umap_gpu = UMAP(n_components=35, n_neighbors=100, random_state=42, output_type='numpy', min_dist = 0.01)

# Fit and transform ON THE GPU (2 hours about for 16MIL posts, comp = 50, n_neigh = 15, GPU RAM at ___)
emb_umap = umap_gpu.fit_transform(X_gpu)

# emb_umap is a NumPy array (back on CPU), shape: (n_posts, dimensions)
print(emb_umap.shape)

# Save as .npy
np.save('/content/drive/MyDrive/umap_embeddings_100_35D_100nn_0.01md.npy', emb_umap)
with open('/content/drive/MyDrive/sample_ids_100_35D_100nn_0.01md.json', 'w') as f:
    json.dump(post_ids, f)

#DIMENSIONALITY REDUCTION 0.001md

# Assume sample_embeddings is a NumPy array (float32)
# Convert to cupy (GPU array)

X_gpu = cp.asarray(emb_pca)

# Initialize cuML UMAP
umap_gpu = UMAP(n_components=35, n_neighbors=100, random_state=42, output_type='numpy', min_dist = 0.001)

# Fit and transform ON THE GPU (2 hours about for 16MIL posts, comp = 50, n_neigh = 15, GPU RAM at ___)
emb_umap = umap_gpu.fit_transform(X_gpu)

# emb_umap is a NumPy array (back on CPU), shape: (n_posts, dimensions)
print(emb_umap.shape)

# Save as .npy
np.save('/content/drive/MyDrive/umap_embeddings_100_35D_100nn_0.001md.npy', emb_umap)
with open('/content/drive/MyDrive/sample_ids_100_35D_100nn_0.001md.json', 'w') as f:
    json.dump(post_ids, f)

#DIMENSIONALITY REDUCTION 50nn

# Assume sample_embeddings is a NumPy array (float32)
# Convert to cupy (GPU array)

X_gpu = cp.asarray(emb_pca)

# Initialize cuML UMAP
umap_gpu = UMAP(n_components=35, n_neighbors=50, random_state=42, output_type='numpy', min_dist = 0.1)

# Fit and transform ON THE GPU (2 hours about for 16MIL posts, comp = 50, n_neigh = 15, GPU RAM at ___)
emb_umap = umap_gpu.fit_transform(X_gpu)

# emb_umap is a NumPy array (back on CPU), shape: (n_posts, dimensions)
print(emb_umap.shape)

# Save as .npy
np.save('/content/drive/MyDrive/umap_embeddings_50nn.npy', emb_umap)
with open('/content/drive/MyDrive/sample_ids_50nn.json', 'w') as f:
    json.dump(post_ids, f)

#DIMENSIONALITY REDUCTION 200nn

# Assume sample_embeddings is a NumPy array (float32)
# Convert to cupy (GPU array)

X_gpu = cp.asarray(emb_pca)

# Initialize cuML UMAP
umap_gpu = UMAP(n_components=35, n_neighbors=200, random_state=42, output_type='numpy', min_dist = 0.1)

# Fit and transform ON THE GPU (2 hours about for 16MIL posts, comp = 50, n_neigh = 15, GPU RAM at ___)
emb_umap = umap_gpu.fit_transform(X_gpu)

# emb_umap is a NumPy array (back on CPU), shape: (n_posts, dimensions)
print(emb_umap.shape)

# Save as .npy
np.save('/content/drive/MyDrive/umap_embeddings_100_35D_200nn_0.1md.npy', emb_umap)
with open('/content/drive/MyDrive/sample_ids_100_35D_200nn_0.1md.json', 'w') as f:
    json.dump(post_ids, f)