# -*- coding: utf-8 -*-
"""HDBSCAN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15C5o9Guhc_K87-XqkojEJ76514eGp5T5
"""

#HDBSCAN

import json
import numpy as np
import gc
import pandas as pd
from cuml.cluster import HDBSCAN
from sklearn.preprocessing import normalize
from google.colab import drive
drive.mount('/content/drive')

#BEST Results

#Load embeddings if not in RAM
embeddings = np.load('/content/drive/MyDrive/umap_embeddings_50D_100PCA_10%.npy')
# Load aligned post IDs
with open('/content/drive/MyDrive/sample_ids_50D_100PCA_10%.json') as f:
    post_ids = json.load(f)

#BEST Results

# cuML HDBSCAN expects float32 and contiguous arrays
embeddings = embeddings.astype(np.float32, copy=False)

#HDBSCAN: BEST (min_size = 25; min samples =5; epsilon = 0.1; cluster method: leaf)

# Initialize and fit HDBSCAN (adjust min_cluster_size as needed) (__hrs with min_cluster_size=1000, min_samples=1, metric='euclidean')
hdb_gpu = HDBSCAN(min_cluster_size=25, min_samples=5, cluster_selection_method='leaf', metric='euclidean', cluster_selection_epsilon = 0.09, prediction_data=True)
labels = hdb_gpu.fit_predict(embeddings)  # shape: (n_posts,)

# Convert to CPU numpy if needed
labels = labels.get() if hasattr(labels, 'get') else labels

print("Number of clusters (excluding noise):", len(set(labels)) - (1 if -1 in labels else 0))

# Save as JSON

df = pd.DataFrame({
    "post_id": post_ids,
    "cluster": labels
})
df.to_json('/content/drive/MyDrive/umap_10%_50D_100PCA_SIZE25_EPS.1_SAMP5_nn100.json', orient="records", lines=True)

#HDBSCAN WITH PROB ASSIGNMENTS

# Initialize HDBSCAN with prediction_data=True to allow membership vector calculation
hdb_gpu = HDBSCAN(
    min_cluster_size=25,
    min_samples=5,
    cluster_selection_method='leaf',
    metric='euclidean',
    cluster_selection_epsilon=0.09,
    prediction_data=True  # Required for membership vectors
)

labels = hdb_gpu.fit_predict(embeddings)

# 1. Get the Soft Clustering / Membership Vectors
# This returns an array of shape (n_samples, n_clusters)
# Each row contains the probability of that point belonging to each cluster
membership_vectors = hdb_gpu.all_points_membership_vectors()

# Convert to CPU numpy
membership_vectors_cpu = membership_vectors.get() if hasattr(membership_vectors, 'get') else membership_vectors
labels_cpu = labels.get() if hasattr(labels, 'get') else labels

# 2. Create a DataFrame with the probability distribution
# Each column will represent a cluster (0, 1, 2...)
prob_columns = [f"cluster_{i}_prob" for i in range(membership_vectors_cpu.shape[1])]
df_probs = pd.DataFrame(membership_vectors_cpu, columns=prob_columns)

# Add the original IDs and the hard labels
df_probs.insert(0, "post_id", post_ids)
df_probs.insert(1, "hard_label", labels_cpu)

# 3. Save as JSON (Warning: this file will be significantly larger)
df_probs.to_json('/content/drive/MyDrive/umap_10%_probs_full.json', orient="records", lines=True)

print(f"Probabilities matrix shape: {membership_vectors_cpu.shape}")

#BIRCH & SPEC CLUSTERING

from cuml.cluster import Birch, SpectralClustering

# 1. BIRCH Implementation (Middle Ground)
# 'threshold' is the max radius of a theme; adjust this to control granularity.
birch_gpu = Birch(n_clusters=100, threshold=0.5, branching_factor=50)
birch_labels = birch_gpu.fit_predict(embeddings)

# 2. Spectral Clustering Implementation (High-Quality Shapes, No Noise)
# 'affinity' can be 'rbf' (radial) or 'nearest_neighbors' for graph-based logic.
spectral_gpu = SpectralClustering(n_clusters=50, affinity='nearest_neighbors', n_neighbors=20)
spectral_labels = spectral_gpu.fit_predict(embeddings)

# Clean up GPU memory
del birch_gpu, spectral_gpu
gc.collect()

#DIM-REDUC CONTROL

#_________________

#Load embeddings if not in RAM
embeddings = np.load('/content/drive/MyDrive/umap_embeddings_CONTROL.npy')
# Load aligned post IDs
with open('/content/drive/MyDrive/sample_ids_CONTROL.json') as f:
    post_ids = json.load(f)

#PCA

#_________________

"""del embeddings
gc.collect()
del post_ids
gc.collect()"""

"""#NOPCA
#Load embeddings if not in RAM
embeddings = np.load('/content/drive/MyDrive/umap_embeddings_NOPCA.npy')
# Load aligned post IDs
with open('/content/drive/MyDrive/sample_ids_NOPCA.json') as f:
    post_ids = json.load(f)
"""
"""
#PCA150
#Load embeddings if not in RAM
embeddings = np.load('/content/drive/MyDrive/umap_embeddings_PCA150.npy')
# Load aligned post IDs
with open('/content/drive/MyDrive/sample_ids_PCA150.json') as f:
    post_ids = json.load(f)
"""

#PCA200
#Load embeddings if not in RAM
embeddings = np.load('/content/drive/MyDrive/umap_embeddings_PCA200.npy')
# Load aligned post IDs
with open('/content/drive/MyDrive/sample_ids_PCA200.json') as f:
    post_ids = json.load(f)

#MIN_DIST

#_________________
'''del embeddings
gc.collect()
del post_ids
gc.collect()'''


#0.25
#Load embeddings if not in RAM
embeddings = np.load('/content/drive/MyDrive/umap_embeddings_0.25md.npy')
# Load aligned post IDs
with open('/content/drive/MyDrive/sample_ids_0.25md.json') as f:
    post_ids = json.load(f)

"""
#0.01
#Load embeddings if not in RAM
embeddings = np.load('/content/drive/MyDrive/umap_embeddings_0.01md.npy')
# Load aligned post IDs
with open('/content/drive/MyDrive/sample_ids_0.01md.json') as f:
    post_ids = json.load(f)
"""
"""
#0.001
#Load embeddings if not in RAM
embeddings = np.load('/content/drive/MyDrive/umap_embeddings_0.001md.npy')
# Load aligned post IDs
with open('/content/drive/MyDrive/sample_ids_0.001md.json') as f:
    post_ids = json.load(f)
"""

#NEAREST NEIGHBORS

#_________________
"""
#50nn
#Load embeddings if not in RAM
embeddings = np.load('/content/drive/MyDrive/umap_embeddings_50nn.npy')
# Load aligned post IDs
with open('/content/drive/MyDrive/sample_ids_50nn.json') as f:
    post_ids = json.load(f)

"""
#200nn
#Load embeddings if not in RAM
embeddings = np.load('/content/drive/MyDrive/umap_embeddings_200nn.npy')
# Load aligned post IDs
with open('/content/drive/MyDrive/sample_ids_200nn.json') as f:
    post_ids = json.load(f)

#SANINTY CHECK

print(embeddings.shape)

assert embeddings.shape[0] == len(post_ids), "Mismatch between embeddings and post_ids!"

# cuML HDBSCAN expects float32 and contiguous arrays
embeddings = embeddings.astype(np.float32, copy=False)

#HDBSCAN: CONTROL (min_size = 1000; min samples =15; epsilon = 0.0; cluster method: eom)

# Initialize and fit HDBSCAN (adjust min_cluster_size as needed) (__hrs with min_cluster_size=1000, min_samples=1, metric='euclidean')
hdb_gpu = HDBSCAN(min_cluster_size=1000, min_samples=15, cluster_selection_method='eom', metric='euclidean', prediction_data=True)
labels = hdb_gpu.fit_predict(embeddings)  # shape: (n_posts,)

# Convert to CPU numpy if needed
labels = labels.get() if hasattr(labels, 'get') else labels

print("Number of clusters (excluding noise):", len(set(labels)) - (1 if -1 in labels else 0))

# Save as JSON

df = pd.DataFrame({
    "post_id": post_ids,
    "cluster": labels
})
df.to_json('/content/drive/MyDrive/umap_10%_NN200_CONTROL.json', orient="records", lines=True)

#HDBSCAN: METHOD = LEAF

# Initialize and fit HDBSCAN (adjust min_cluster_size as needed) (__hrs with min_cluster_size=1000, min_samples=1, metric='euclidean')
hdb_gpu = HDBSCAN(min_cluster_size=1000, min_samples=15, cluster_selection_method='leaf', metric='euclidean')
labels = hdb_gpu.fit_predict(embeddings)  # shape: (n_posts,)

# Convert to CPU numpy if needed
labels = labels.get() if hasattr(labels, 'get') else labels

print("Number of clusters (excluding noise):", len(set(labels)) - (1 if -1 in labels else 0))

# Save as JSON

df = pd.DataFrame({
    "post_id": post_ids,
    "cluster": labels
})
df.to_json('/content/drive/MyDrive/umap_10%_NN200_LEAF.json', orient="records", lines=True)

#HDBSCAN: CLUSTERING SIZE = 100

# Initialize and fit HDBSCAN (adjust min_cluster_size as needed) (__hrs with min_cluster_size=1000, min_samples=1, metric='euclidean')
hdb_gpu = HDBSCAN(min_cluster_size=100, min_samples=15, cluster_selection_method='eom', metric='euclidean')
labels = hdb_gpu.fit_predict(embeddings)  # shape: (n_posts,)

# Convert to CPU numpy if needed
labels = labels.get() if hasattr(labels, 'get') else labels

print("Number of clusters (excluding noise):", len(set(labels)) - (1 if -1 in labels else 0))

# Save as JSON

df = pd.DataFrame({
    "post_id": post_ids,
    "cluster": labels
})
df.to_json('/content/drive/MyDrive/umap_10%_NN200_SIZE100.json', orient="records", lines=True)

#HDBSCAN: CLUSTERING SIZE = 50

# Initialize and fit HDBSCAN (adjust min_cluster_size as needed) (__hrs with min_cluster_size=1000, min_samples=1, metric='euclidean')
hdb_gpu = HDBSCAN(min_cluster_size=50, min_samples=15, cluster_selection_method='eom', metric='euclidean')
labels = hdb_gpu.fit_predict(embeddings)  # shape: (n_posts,)

# Convert to CPU numpy if needed
labels = labels.get() if hasattr(labels, 'get') else labels

print("Number of clusters (excluding noise):", len(set(labels)) - (1 if -1 in labels else 0))

# Save as JSON

df = pd.DataFrame({
    "post_id": post_ids,
    "cluster": labels
})
df.to_json('/content/drive/MyDrive/umap_10%_NN200_SIZE50.json', orient="records", lines=True)

#HDBSCAN: SAMPLES = 1 (tends to take longer )

# Initialize and fit HDBSCAN (adjust min_cluster_size as needed) (__hrs with min_cluster_size=1000, min_samples=1, metric='euclidean')
hdb_gpu = HDBSCAN(min_cluster_size=1000, min_samples=1, cluster_selection_method='eom', metric='euclidean')
labels = hdb_gpu.fit_predict(embeddings)  # shape: (n_posts,)

# Convert to CPU numpy if needed
labels = labels.get() if hasattr(labels, 'get') else labels

print("Number of clusters (excluding noise):", len(set(labels)) - (1 if -1 in labels else 0))

# Save as JSON

df = pd.DataFrame({
    "post_id": post_ids,
    "cluster": labels
})
df.to_json('/content/drive/MyDrive/umap_10%_MD0.25_1SAMPLES.json', orient="records", lines=True)

#HDBSCAN: SAMPLES = 100

# Initialize and fit HDBSCAN (adjust min_cluster_size as needed) (__hrs with min_cluster_size=1000, min_samples=1, metric='euclidean')
hdb_gpu = HDBSCAN(min_cluster_size=1000, min_samples=100, cluster_selection_method='eom', metric='euclidean')
labels = hdb_gpu.fit_predict(embeddings)  # shape: (n_posts,)

# Convert to CPU numpy if needed
labels = labels.get() if hasattr(labels, 'get') else labels

print("Number of clusters (excluding noise):", len(set(labels)) - (1 if -1 in labels else 0))

# Save as JSON

df = pd.DataFrame({
    "post_id": post_ids,
    "cluster": labels
})
df.to_json('/content/drive/MyDrive/umap_10%_NN200_100SAMPLES.json', orient="records", lines=True)

#HDBSCAN: EPSILON = 0.01

# Initialize and fit HDBSCAN (adjust min_cluster_size as needed) (__hrs with min_cluster_size=1000, min_samples=1, metric='euclidean')
hdb_gpu = HDBSCAN(min_cluster_size=1000, min_samples=15, cluster_selection_method='eom', cluster_selection_epsilon=0.01, metric='euclidean')
labels = hdb_gpu.fit_predict(embeddings)  # shape: (n_posts,)

# Convert to CPU numpy if needed
labels = labels.get() if hasattr(labels, 'get') else labels

print("Number of clusters (excluding noise):", len(set(labels)) - (1 if -1 in labels else 0))

# Save as JSON

df = pd.DataFrame({
    "post_id": post_ids,
    "cluster": labels
})
df.to_json('/content/drive/MyDrive/umap_10%_NN200_EPSILON.01.json', orient="records", lines=True)

#HDBSCAN: EPSILON = 0.1

# Initialize and fit HDBSCAN (adjust min_cluster_size as needed) (__hrs with min_cluster_size=1000, min_samples=1, metric='euclidean')
hdb_gpu = HDBSCAN(min_cluster_size=1000, min_samples=15, cluster_selection_method='eom', cluster_selection_epsilon=0.1, metric='euclidean')
labels = hdb_gpu.fit_predict(embeddings)  # shape: (n_posts,)

# Convert to CPU numpy if needed
labels = labels.get() if hasattr(labels, 'get') else labels

print("Number of clusters (excluding noise):", len(set(labels)) - (1 if -1 in labels else 0))

# Save as JSON

df = pd.DataFrame({
    "post_id": post_ids,
    "cluster": labels
})
df.to_json('/content/drive/MyDrive/umap_10%_NN200_EPSILON.1.json', orient="records", lines=True)