# -*- coding: utf-8 -*-
"""KMeans.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KWokBEIk9QVBST_ducZHDvYuUAd9XmM8
"""

#KMEANS
from sklearn.decomposition import PCA
import json
import numpy as np
import cupy as cp
from cuml.cluster import KMeans
import gc
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

#BEST Results

#Load embeddings if not in RAM
embeddings = np.load('/content/drive/MyDrive/all_embeddings_clean.npy')
# Load aligned post IDs
with open('/content/drive/MyDrive/all_ids_clean.json') as f:
    post_ids = json.load(f)

pca = PCA(n_components=150, random_state=42)
emb_pca = pca.fit_transform(embeddings)
#del sample_indices; gc.collect()
del embeddings; gc.collect()
embeddings = emb_pca.astype(np.float32, copy=False)
np.save('/content/drive/MyDrive/all_embeddings_150PCA.npy', emb_pca)

#BEST Results

# cuML KMeans expects float32 and contiguous arrays
embeddings = embeddings.astype(np.float32, copy=False)

X_gpu = cp.asarray(embeddings)
del embeddings
gc.collect()
# Set number of clusters
n_clusters = 250

# Initialize KMeans model
kmeans_gpu = KMeans(n_clusters=n_clusters, random_state=42, verbose=1)  # verbose for progress

# Fit and predict cluster assignments (returns cupy array)
labels_gpu = kmeans_gpu.fit_predict(X_gpu)

# Move labels to CPU numpy
labels = cp.asnumpy(labels_gpu)

print(f"Assigned {n_clusters} clusters to {len(labels)} points.")

# Save as JSON

df = pd.DataFrame({
    "post_id": post_ids,
    "cluster": labels
})
df.to_json('/content/drive/MyDrive/.json', orient="records", lines=True)

#DIM-REDUC CONTROL

#_________________

#Load embeddings if not in RAM
embeddings = np.load('/content/drive/MyDrive/umap_embeddings_CONTROL.npy')
# Load aligned post IDs
with open('/content/drive/MyDrive/sample_ids_CONTROL.json') as f:
    post_ids = json.load(f)

#PCA

#_________________

"""del embeddings
gc.collect()
del post_ids
gc.collect()"""

"""#NOPCA
#Load embeddings if not in RAM
embeddings = np.load('/content/drive/MyDrive/umap_embeddings_NOPCA.npy')
# Load aligned post IDs
with open('/content/drive/MyDrive/sample_ids_NOPCA.json') as f:
    post_ids = json.load(f)
"""
"""
#PCA150
#Load embeddings if not in RAM
embeddings = np.load('/content/drive/MyDrive/umap_embeddings_PCA150.npy')
# Load aligned post IDs
with open('/content/drive/MyDrive/sample_ids_PCA150.json') as f:
    post_ids = json.load(f)
"""

#PCA200
#Load embeddings if not in RAM
embeddings = np.load('/content/drive/MyDrive/umap_embeddings_PCA200.npy')
# Load aligned post IDs
with open('/content/drive/MyDrive/sample_ids_PCA200.json') as f:
    post_ids = json.load(f)

#MIN_DIST

#_________________
'''del embeddings
gc.collect()
del post_ids
gc.collect()'''


#0.25
#Load embeddings if not in RAM
embeddings = np.load('/content/drive/MyDrive/umap_embeddings_0.25md.npy')
# Load aligned post IDs
with open('/content/drive/MyDrive/sample_ids_0.25md.json') as f:
    post_ids = json.load(f)

"""
#0.01
#Load embeddings if not in RAM
embeddings = np.load('/content/drive/MyDrive/umap_embeddings_0.01md.npy')
# Load aligned post IDs
with open('/content/drive/MyDrive/sample_ids_0.01md.json') as f:
    post_ids = json.load(f)
"""
"""
#0.001
#Load embeddings if not in RAM
embeddings = np.load('/content/drive/MyDrive/umap_embeddings_0.001md.npy')
# Load aligned post IDs
with open('/content/drive/MyDrive/sample_ids_0.001md.json') as f:
    post_ids = json.load(f)
"""

#NEAREST NEIGHBORS

#_________________
"""
#50nn
#Load embeddings if not in RAM
embeddings = np.load('/content/drive/MyDrive/umap_embeddings_50nn.npy')
# Load aligned post IDs
with open('/content/drive/MyDrive/sample_ids_50nn.json') as f:
    post_ids = json.load(f)

"""
#200nn
#Load embeddings if not in RAM
embeddings = np.load('/content/drive/MyDrive/umap_embeddings_200nn.npy')
# Load aligned post IDs
with open('/content/drive/MyDrive/sample_ids_200nn.json') as f:
    post_ids = json.load(f)

#SANINTY CHECK

print(embeddings.shape)

assert embeddings.shape[0] == len(post_ids), "Mismatch between embeddings and post_ids!"

# cuML HDBSCAN expects float32 and contiguous arrays
embeddings = embeddings.astype(np.float32, copy=False)

#HDBSCAN: CONTROL (min_size = 1000; min samples =15; epsilon = 0.0; cluster method: eom)

# Initialize and fit HDBSCAN (adjust min_cluster_size as needed) (__hrs with min_cluster_size=1000, min_samples=1, metric='euclidean')
hdb_gpu = HDBSCAN(min_cluster_size=1000, min_samples=15, cluster_selection_method='eom', metric='euclidean')
labels = hdb_gpu.fit_predict(embeddings)  # shape: (n_posts,)

# Convert to CPU numpy if needed
labels = labels.get() if hasattr(labels, 'get') else labels

print("Number of clusters (excluding noise):", len(set(labels)) - (1 if -1 in labels else 0))

# Save as JSON

df = pd.DataFrame({
    "post_id": post_ids,
    "cluster": labels
})
df.to_json('/content/drive/MyDrive/umap_10%_NN200_CONTROL.json', orient="records", lines=True)

#HDBSCAN: METHOD = LEAF

# Initialize and fit HDBSCAN (adjust min_cluster_size as needed) (__hrs with min_cluster_size=1000, min_samples=1, metric='euclidean')
hdb_gpu = HDBSCAN(min_cluster_size=1000, min_samples=15, cluster_selection_method='leaf', metric='euclidean')
labels = hdb_gpu.fit_predict(embeddings)  # shape: (n_posts,)

# Convert to CPU numpy if needed
labels = labels.get() if hasattr(labels, 'get') else labels

print("Number of clusters (excluding noise):", len(set(labels)) - (1 if -1 in labels else 0))

# Save as JSON

df = pd.DataFrame({
    "post_id": post_ids,
    "cluster": labels
})
df.to_json('/content/drive/MyDrive/umap_10%_NN200_LEAF.json', orient="records", lines=True)

#HDBSCAN: CLUSTERING SIZE = 100

# Initialize and fit HDBSCAN (adjust min_cluster_size as needed) (__hrs with min_cluster_size=1000, min_samples=1, metric='euclidean')
hdb_gpu = HDBSCAN(min_cluster_size=100, min_samples=15, cluster_selection_method='eom', metric='euclidean')
labels = hdb_gpu.fit_predict(embeddings)  # shape: (n_posts,)

# Convert to CPU numpy if needed
labels = labels.get() if hasattr(labels, 'get') else labels

print("Number of clusters (excluding noise):", len(set(labels)) - (1 if -1 in labels else 0))

# Save as JSON

df = pd.DataFrame({
    "post_id": post_ids,
    "cluster": labels
})
df.to_json('/content/drive/MyDrive/umap_10%_NN200_SIZE100.json', orient="records", lines=True)

#HDBSCAN: CLUSTERING SIZE = 50

# Initialize and fit HDBSCAN (adjust min_cluster_size as needed) (__hrs with min_cluster_size=1000, min_samples=1, metric='euclidean')
hdb_gpu = HDBSCAN(min_cluster_size=50, min_samples=15, cluster_selection_method='eom', metric='euclidean')
labels = hdb_gpu.fit_predict(embeddings)  # shape: (n_posts,)

# Convert to CPU numpy if needed
labels = labels.get() if hasattr(labels, 'get') else labels

print("Number of clusters (excluding noise):", len(set(labels)) - (1 if -1 in labels else 0))

# Save as JSON

df = pd.DataFrame({
    "post_id": post_ids,
    "cluster": labels
})
df.to_json('/content/drive/MyDrive/umap_10%_NN200_SIZE50.json', orient="records", lines=True)

#HDBSCAN: SAMPLES = 1 (tends to take longer )

# Initialize and fit HDBSCAN (adjust min_cluster_size as needed) (__hrs with min_cluster_size=1000, min_samples=1, metric='euclidean')
hdb_gpu = HDBSCAN(min_cluster_size=1000, min_samples=1, cluster_selection_method='eom', metric='euclidean')
labels = hdb_gpu.fit_predict(embeddings)  # shape: (n_posts,)

# Convert to CPU numpy if needed
labels = labels.get() if hasattr(labels, 'get') else labels

print("Number of clusters (excluding noise):", len(set(labels)) - (1 if -1 in labels else 0))

# Save as JSON

df = pd.DataFrame({
    "post_id": post_ids,
    "cluster": labels
})
df.to_json('/content/drive/MyDrive/umap_10%_MD0.25_1SAMPLES.json', orient="records", lines=True)

#HDBSCAN: SAMPLES = 100

# Initialize and fit HDBSCAN (adjust min_cluster_size as needed) (__hrs with min_cluster_size=1000, min_samples=1, metric='euclidean')
hdb_gpu = HDBSCAN(min_cluster_size=1000, min_samples=100, cluster_selection_method='eom', metric='euclidean')
labels = hdb_gpu.fit_predict(embeddings)  # shape: (n_posts,)

# Convert to CPU numpy if needed
labels = labels.get() if hasattr(labels, 'get') else labels

print("Number of clusters (excluding noise):", len(set(labels)) - (1 if -1 in labels else 0))

# Save as JSON

df = pd.DataFrame({
    "post_id": post_ids,
    "cluster": labels
})
df.to_json('/content/drive/MyDrive/umap_10%_NN200_100SAMPLES.json', orient="records", lines=True)

#HDBSCAN: EPSILON = 0.01

# Initialize and fit HDBSCAN (adjust min_cluster_size as needed) (__hrs with min_cluster_size=1000, min_samples=1, metric='euclidean')
hdb_gpu = HDBSCAN(min_cluster_size=1000, min_samples=15, cluster_selection_method='eom', cluster_selection_epsilon=0.01, metric='euclidean')
labels = hdb_gpu.fit_predict(embeddings)  # shape: (n_posts,)

# Convert to CPU numpy if needed
labels = labels.get() if hasattr(labels, 'get') else labels

print("Number of clusters (excluding noise):", len(set(labels)) - (1 if -1 in labels else 0))

# Save as JSON

df = pd.DataFrame({
    "post_id": post_ids,
    "cluster": labels
})
df.to_json('/content/drive/MyDrive/umap_10%_NN200_EPSILON.01.json', orient="records", lines=True)

#HDBSCAN: EPSILON = 0.1

# Initialize and fit HDBSCAN (adjust min_cluster_size as needed) (__hrs with min_cluster_size=1000, min_samples=1, metric='euclidean')
hdb_gpu = HDBSCAN(min_cluster_size=1000, min_samples=15, cluster_selection_method='eom', cluster_selection_epsilon=0.1, metric='euclidean')
labels = hdb_gpu.fit_predict(embeddings)  # shape: (n_posts,)

# Convert to CPU numpy if needed
labels = labels.get() if hasattr(labels, 'get') else labels

print("Number of clusters (excluding noise):", len(set(labels)) - (1 if -1 in labels else 0))

# Save as JSON

df = pd.DataFrame({
    "post_id": post_ids,
    "cluster": labels
})
df.to_json('/content/drive/MyDrive/umap_10%_NN200_EPSILON.1.json', orient="records", lines=True)